DROP TABLE IF EXISTS password_reset_tokens;
DROP TABLE IF EXISTS auth_email_tokens;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS projects;
